# Generated by Django 4.0.4 on 2022-05-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='net_price',
            field=models.IntegerField(blank=True),
        ),
    ]
